### ISSUE TITLE
CSV export timeout with on large sites

### ISSUE THREAD

**Issue by scott-nz** [silverstripe/silverstripe-sitewidecontent-report#39]
Pages CSV export fails due to PHP timeout on large sites - error occurring on site with > 2000 pages

Files CSV export fails due to PHP timeout on large sites - error occurring on site with > 2000 files

This issue exists in 2.x and 3.x release lines.
If PHP timeout is disabled the exports are successfully generated.

**Edit: Solution**
1. Ensure the module is compatible with [gridfieldqueuedexport](https://github.com/silverstripe/silverstripe-gridfieldqueuedexport) and can be enabled in project code for people with large datasets 
2. Update the documentation to reference this optional module, and describe in what scenarios it makes sense to use

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/42 (nice to have)
- [x] https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/40

**Comment by robbieaverill** [comment]
Thanks for the bug report. I suspect that this is a problem with the export CSV handler in core, given that we're simply reusing it in this module. I think we should move this issue into framework. What do you think?

Good to know raising your PHP timeout limit works. I wouldn't recommend disabling it entirely.

**Comment by NightJar** [comment]
Ideally export tasks would use queued jobs if installed to avoid this issue entirely :)
I'm not sure where that issue would live though. Perhaps it could be done here?

**Comment by scott-nz** [comment]
changing this module to use https://github.com/silverstripe/silverstripe-gridfieldqueuedexport could be an option

**Comment by robbieaverill** [comment]
We could fix this here, but the same thing would happen with any GridField you try to export with enough data in it. I think what we need to do for this is to ensure the module is compatible with gridfieldqueuedexport and can be enabled in project code for people with large datasets - the documentation should make this clear and easy.

**Comment by ScopeyNZ** [comment]
I've merged #40 (but not the "nice to have"). I'll close this as fixed by #40 in the next release.
