### ISSUE TITLE
Orphaned page type throws error on Terms method

### ISSUE THREAD

**Issue by HeyImPhil** [silverstripe/silverstripe-sitewidecontent-report#77]
### Module version(s) affected

3.3.0

### Description

This seems to be related to a combination of things. The SitewideContentTaxonomy class needs to pass the enabled method which in this case is coming from the CWP module but could happen on custom code using the tag_field.
 
If a page type is removed and the page type is orphaned. The report will fail when it is exported to CSV on this data object because it doesn't find the Terms() on SiteTree.

I am using version 3 but can see this could be an issue on 4 as well.

### How to reproduce

This can be reproduced by removing a page type that is in use and then exporting the report to csv. This fires the Terms() check on SiteTree instead of the page type as it is removed throwing the following error: `[Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'Terms' does not exist on 'SilverStripe\CMS\Model\SiteTree'` 

1. Delete a page type that is in use (Pages are assigned to it)
2. Generate report
3. Export report
4. Throws Error 

#### Pull Request
https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/78

Line 51 SitewideContentTaxonomy.php
```php
'datasource' => function ($record) use ($field) {
    if ($record->hasMethod($field)) {
        $tags = $record->$field()->column('Name');

        return implode(', ', $tags);
    }

    return '';
},
``` 

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
I haven't spent the time to validate this - but your suggested fix sounds sensible. If you'd like to raise a pull request I'll be happy to review it.

**Comment by GuySartorelli** [comment]
PR merged. This will be tagged automatically by GitHub actions
